-- Groupes de discussion dans le chat d'équipe.
-- À exécuter dans Supabase → SQL Editor.

-- 1. Table des groupes
create table if not exists chat_channels (
  id bigint generated by default as identity primary key,
  team_id bigint references teams(id) on delete cascade,
  name text not null,
  roles text[] not null default '{manager,prepa,kine,coach}',
  created_by uuid references auth.users(id),
  created_at timestamptz default now()
);

-- 2. Les messages peuvent appartenir à un groupe (null = canal général Équipe)
alter table team_messages add column if not exists channel_id bigint references chat_channels(id) on delete cascade;

-- 3. Sécurité des groupes
alter table chat_channels enable row level security;

-- Un membre de l'équipe voit un groupe seulement si son rôle y donne accès
create policy "members see their channels" on chat_channels
  for select using (
    exists (
      select 1 from team_members tm
      where tm.team_id = chat_channels.team_id
        and tm.user_id = auth.uid()
        and tm.role = any(chat_channels.roles)
    )
  );

-- Seuls managers et entraîneurs créent des groupes
create policy "staff create channels" on chat_channels
  for insert with check (
    exists (
      select 1 from team_members tm
      where tm.team_id = chat_channels.team_id
        and tm.user_id = auth.uid()
        and tm.role in ('manager', 'coach')
    )
  );

-- Le créateur ou un manager peut supprimer un groupe
create policy "creator or manager delete channels" on chat_channels
  for delete using (
    created_by = auth.uid()
    or exists (
      select 1 from team_members tm
      where tm.team_id = chat_channels.team_id
        and tm.user_id = auth.uid()
        and tm.role = 'manager'
    )
  );

-- 4. Verrou sur les messages : un message posté dans un groupe n'est lisible
--    que par les rôles du groupe (policy restrictive : s'ajoute aux règles existantes)
create policy "channel messages restricted" on team_messages
  as restrictive for select using (
    channel_id is null
    or exists (
      select 1 from chat_channels c
      join team_members tm on tm.team_id = c.team_id and tm.user_id = auth.uid()
      where c.id = team_messages.channel_id
        and tm.role = any(c.roles)
    )
  );
