-- Tests personnalisés du préparateur physique (par équipe).
-- À exécuter dans Supabase → SQL Editor.

create table if not exists custom_tests (
  id bigint generated by default as identity primary key,
  team_id bigint references teams(id) on delete cascade,
  created_by uuid references auth.users(id),
  name text not null,
  unit text default 'kg',
  icon text default '🧪',
  lower_is_better boolean default false,
  created_at timestamptz default now()
);

create table if not exists custom_test_results (
  id bigint generated by default as identity primary key,
  test_id bigint references custom_tests(id) on delete cascade,
  team_id bigint references teams(id) on delete cascade,
  player_id uuid references auth.users(id),
  saisie_par uuid references auth.users(id),
  date date not null,
  value numeric,
  created_at timestamptz default now()
);

alter table custom_tests enable row level security;
alter table custom_test_results enable row level security;

-- Tous les membres de l'équipe voient les définitions de tests
create policy "team members read custom tests" on custom_tests
  for select using (
    exists (
      select 1 from team_members tm
      where tm.team_id = custom_tests.team_id and tm.user_id = auth.uid()
    )
  );

-- Le prépa de l'équipe crée / modifie / supprime ses tests
create policy "prepa manages custom tests" on custom_tests
  for all using (
    exists (
      select 1 from team_members tm
      where tm.team_id = custom_tests.team_id and tm.user_id = auth.uid() and tm.role = 'prepa'
    )
  ) with check (
    exists (
      select 1 from team_members tm
      where tm.team_id = custom_tests.team_id and tm.user_id = auth.uid() and tm.role = 'prepa'
    )
  );

-- Le joueur voit ses résultats ; le staff de l'équipe les voit aussi
create policy "player or staff read results" on custom_test_results
  for select using (
    player_id = auth.uid()
    or exists (
      select 1 from team_members tm
      where tm.team_id = custom_test_results.team_id
        and tm.user_id = auth.uid()
        and tm.role in ('prepa', 'manager', 'coach', 'kine')
    )
  );

-- Le prépa saisit / corrige / supprime les résultats
create policy "prepa manages results" on custom_test_results
  for all using (
    exists (
      select 1 from team_members tm
      where tm.team_id = custom_test_results.team_id and tm.user_id = auth.uid() and tm.role = 'prepa'
    )
  ) with check (
    exists (
      select 1 from team_members tm
      where tm.team_id = custom_test_results.team_id and tm.user_id = auth.uid() and tm.role = 'prepa'
    )
  );
