-- Messages privés entre membres d'une même équipe.
-- À exécuter dans Supabase → SQL Editor.

create table if not exists direct_messages (
  id bigint generated by default as identity primary key,
  team_id bigint references teams(id) on delete cascade,
  sender_id uuid references auth.users(id),
  recipient_id uuid references auth.users(id),
  message text not null,
  created_at timestamptz default now()
);

alter table direct_messages enable row level security;

-- Seuls l'expéditeur et le destinataire peuvent lire la conversation
create policy "participants read dms" on direct_messages
  for select using (sender_id = auth.uid() or recipient_id = auth.uid());

-- On ne peut écrire qu'en son propre nom, à un membre de la même équipe
create policy "team members send dms" on direct_messages
  for insert with check (
    sender_id = auth.uid()
    and exists (
      select 1 from team_members tm
      where tm.team_id = direct_messages.team_id and tm.user_id = auth.uid()
    )
    and exists (
      select 1 from team_members tm2
      where tm2.team_id = direct_messages.team_id and tm2.user_id = direct_messages.recipient_id
    )
  );

-- L'expéditeur peut supprimer ses propres messages
create policy "sender deletes own dms" on direct_messages
  for delete using (sender_id = auth.uid());
