-- Check-in santé post-match ("Pas de bobo ?").
-- À exécuter dans Supabase → SQL Editor.

create table if not exists match_health_checks (
  id bigint generated by default as identity primary key,
  team_event_id bigint references team_events(id) on delete cascade,
  user_id uuid references auth.users(id),
  status text not null, -- 'ok' ou 'bobo'
  created_at timestamptz default now(),
  unique(team_event_id, user_id)
);

alter table match_health_checks enable row level security;

-- Le joueur répond pour lui-même
create policy "player answers own check" on match_health_checks
  for insert with check (user_id = auth.uid());

-- Le joueur voit ses réponses ; le staff de l'équipe du match les voit aussi
create policy "player or staff read checks" on match_health_checks
  for select using (
    user_id = auth.uid()
    or exists (
      select 1 from team_events e
      join team_members tm on tm.team_id = e.team_id and tm.user_id = auth.uid()
      where e.id = match_health_checks.team_event_id
        and tm.role in ('kine', 'manager', 'coach', 'prepa')
    )
  );
