-- Table des rapports de match publiés par les entraîneurs et managers.
-- À exécuter dans Supabase → SQL Editor (celui où tu avais eu l'erreur "//" —
-- cette fois c'est bien du SQL !)

create table if not exists match_reports (
  id bigint generated by default as identity primary key,
  team_id bigint references teams(id) on delete cascade,
  created_by uuid references auth.users(id),
  author_name text,
  title text not null,
  content text,
  stats jsonb,
  created_at timestamptz default now()
);

alter table match_reports enable row level security;

-- Tous les membres de l'équipe (joueurs et staff) peuvent lire les rapports
create policy "team members read reports" on match_reports
  for select using (
    exists (
      select 1 from team_members tm
      where tm.team_id = match_reports.team_id and tm.user_id = auth.uid()
    )
  );

-- Seuls les entraîneurs et managers de l'équipe peuvent publier
create policy "staff insert reports" on match_reports
  for insert with check (
    exists (
      select 1 from team_members tm
      where tm.team_id = match_reports.team_id
        and tm.user_id = auth.uid()
        and tm.role in ('coach', 'manager')
    )
  );

-- L'auteur peut supprimer son propre rapport
create policy "author delete reports" on match_reports
  for delete using (created_by = auth.uid());
