-- Dossier médical partagé : échange de photos/PDF entre joueur et staff
-- médical, et visibilité du suivi blessures pour tout le staff.
-- À exécuter dans Supabase → SQL Editor.

-- 1. Table des documents médicaux
create table if not exists medical_files (
  id bigint generated by default as identity primary key,
  team_id bigint references teams(id) on delete set null,
  player_id uuid references auth.users(id),
  sender_id uuid references auth.users(id),
  injury_id bigint references injuries(id) on delete set null,
  file_path text not null,
  file_type text default 'photo',
  note text,
  created_at timestamptz default now()
);

alter table medical_files enable row level security;

-- Le joueur voit ses documents ; le staff médical voit ceux des joueurs de ses équipes
create policy "player or medical read files" on medical_files
  for select using (
    player_id = auth.uid()
    or sender_id = auth.uid()
    or exists (
      select 1 from team_members k
      join team_members p on p.team_id = k.team_id and p.user_id = medical_files.player_id
      where k.user_id = auth.uid() and k.role = 'kine'
    )
  );

-- Le joueur envoie pour lui-même ; le staff médical envoie aux joueurs de ses équipes
create policy "player or medical insert files" on medical_files
  for insert with check (
    sender_id = auth.uid()
    and (
      player_id = auth.uid()
      or exists (
        select 1 from team_members k
        join team_members p on p.team_id = k.team_id and p.user_id = medical_files.player_id
        where k.user_id = auth.uid() and k.role = 'kine'
      )
    )
  );

-- L'expéditeur peut supprimer son document
create policy "sender deletes files" on medical_files
  for delete using (sender_id = auth.uid());

-- 2. Espace de stockage PRIVÉ pour les documents médicaux
--    (accessibles uniquement via liens signés temporaires, pas d'URL publique)
insert into storage.buckets (id, name, public) values ('medical', 'medical', false)
on conflict (id) do nothing;

create policy "authenticated upload medical" on storage.objects
  for insert to authenticated with check (bucket_id = 'medical');

create policy "authenticated read medical" on storage.objects
  for select to authenticated using (bucket_id = 'medical');

-- 3. Le lien joueurs ↔ staff : manager, entraîneur et prépa voient aussi
--    les blessures des joueurs de leurs équipes (suivi d'aptitude)
create policy "staff reads team injuries" on injuries
  for select using (
    exists (
      select 1 from team_members s
      join team_members p on p.team_id = s.team_id and p.user_id = injuries.user_id
      where s.user_id = auth.uid() and s.role in ('manager', 'coach', 'prepa')
    )
  );
