-- Réponses de présence des joueurs aux événements d'équipe (team_events).
-- À exécuter dans Supabase → SQL Editor. Montre-le avant d'appliquer.

create table if not exists team_event_attendance (
  id bigint generated by default as identity primary key,
  team_event_id bigint references team_events(id) on delete cascade,
  user_id uuid references auth.users(id),
  team_id bigint references teams(id) on delete cascade,
  statut text not null,                 -- 'present' | 'absent' | 'incertain'
  raison text,                          -- précision optionnelle
  updated_at timestamptz default now(),
  unique(team_event_id, user_id)        -- une seule réponse par joueur et par événement (upsert)
);

alter table team_event_attendance enable row level security;

-- Le joueur écrit UNIQUEMENT sa propre réponse
create policy "player writes own attendance" on team_event_attendance
  for insert with check (user_id = auth.uid());
create policy "player updates own attendance" on team_event_attendance
  for update using (user_id = auth.uid()) with check (user_id = auth.uid());

-- Lecture : sa propre réponse + celles des autres membres de SON équipe (lecture seule)
create policy "team members read attendance" on team_event_attendance
  for select using (
    user_id = auth.uid()
    or exists (
      select 1 from team_members tm
      where tm.team_id = team_event_attendance.team_id
        and tm.user_id = auth.uid()
    )
  );

-- Le joueur peut retirer sa propre réponse
create policy "player deletes own attendance" on team_event_attendance
  for delete using (user_id = auth.uid());
